services:
  postgres:
    image: postgres
    restart: always
    container_name: user_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  user_service:
    image: user_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - '8080:8080'
    depends_on:
      postgresql:
        condition: service_started